DOC for Netconf test tool docker image
FRINXio/frinxio.github.io pull request #173
Opened 2023-04-06 09:10 UTC by ltokarcik

- DOC for running Netconf test tool from docker image on Docker hub

JIRA: UNIC-1159

2023-04-14 04:47 UTC, stanislav-chlebec requested changes

2023-04-14 04:47 UTC, stanislav-chlebec commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
> +To set value of xmx is required to enter xmx heap size value separated from -x or --xmx option.
i do not quite understand.
what does mean separated in the context of all sentence?
ahhh i remember
you mean there must be a space between keyword and value.
please rephrase e.g.
while using xmx option you must use space before entered value

2023-04-14 04:47 UTC, stanislav-chlebec commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
> +            --md-sal true
please add missing backslash at the end

2023-04-14 04:47 UTC, stanislav-chlebec commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
> +-it --entrypoint /bin/bash frinx/netconf-testtool
please add backslash

2023-04-14 04:47 UTC, stanislav-chlebec commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
> +
please add backslash

2023-04-21 10:23 UTC, marosmars approved these changes

2023-04-21 10:26 UTC, merged