DOC for Unhide and Hide commands in Uniconfig shell
FRINXio/frinxio.github.io pull request #203
Opened 2023-10-20 14:35 UTC by ltokarcik

2023-10-25 10:50 UTC, jbogusciak requested changes

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +* Command 'unhide-set' is used to unhide attribute that was hidden in application properties for write.
an attribute

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +* Command 'hide-set' is used to hide again unhidden attribute with 'unhide-set' command.
remove 'again'

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +  (In this example is unhide parameter set to 'all')
"In this example, the unhide parameter is set to 'all' "

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +Command also confirm that attribute was added or removed from unhidden list.
The command also confirms that the attribute

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +When is 'unhide-get' or 'hide-get' called without parameter, then output contains list of all unhidden parameters.
When 'unhide-get' or 'hide-get' is called without a parameter, then the output contains a list ....

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +It is simillar also for 'unhide-set' and 'hide-set' commands.
It is also similar to 'unhide-set' and 'hide-set' commands.

2023-10-25 10:50 UTC, jbogusciak commented on frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
> +There could be used also parameter all, that unhide all parameters for read or for write that are defined in application properties.
The 'all' parameter could also be used, which unhides all parameters for read or for write that are defined in application properties.

2023-10-27 12:19 UTC, knuuzor reviewed
Copy check OK

2023-10-30 11:08 UTC, merged