Rewrite metrics to prometheus.
FRINXio/frinxio.github.io pull request #253
Opened 2024-11-18 12:49 UTC by BranislavMalo

2024-11-18 12:50 UTC, BranislavMalo commented
Reviewer: @MatejGlemba

2024-11-18 12:53 UTC, MatejGlemba approved these changes

2024-11-19 09:49 UTC, puskarpeter commented on frinx-uniconfig/developer-guide/metrics/readme.md
> +Tags are currently not available in the version *7.0.x*, although support for them is planned for future major release.
You can remove the whole tag section, this was related to the version of dropwizard metrics.

2024-11-19 09:50 UTC, puskarpeter requested changes
Just remove the tag section, not relevant anymore, otherwise everything seems ok.

2024-11-19 12:04 UTC, puskarpeter approved these changes

2024-11-19 12:04 UTC, merged