Default parameters
FRINXio/frinxio.github.io pull request #8
Opened 2022-01-31 14:13 UTC by MatejGlemba

@jaro0149 @matkuliak

2022-02-01 07:19 UTC, matkuliak requested changes

2022-02-01 07:19 UTC, matkuliak commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md
> +REST
RPC format still needs to be fixed

2022-02-04 09:20 UTC, MatejGlemba commented on frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md
> +REST
resolved

2022-02-04 09:27 UTC, matkuliak approved these changes
lgtm

2022-02-04 09:27 UTC, merged